import '@/styles/globals.scss'
import styles from '@/styles/contact.module.scss'

import { Header } from '@/components'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Henrique Garcia | Contato',
  description: 'Generated by create next app'
}

export default function ContactLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <div className={styles.contact_page}>
          <Header contact />

          {children}

          <div className={styles.contact__background}>
            <img src="/images/background_01.png" alt="" />
          </div>
        </div>
      </body>
    </html>
  )
}
