import '@/styles/globals.scss'

import { BlogProviders } from './providers'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Henrique Garcia | Coleções',
  description: 'Generated by create next app'
}

export default function BlogLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <BlogProviders>{children}</BlogProviders>
      </body>
    </html>
  )
}
